apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: techcorp-network-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: techcorp
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - ports:
    - protocol: TCP
      port: 5000
  egress:
  - ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80
    - protocol: UDP
      port: 53
