apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: techcorp-pvc
  labels:
    app: techcorp
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi