apiVersion: v1
kind: Service
metadata:
  name: techcorp-service
  labels:
    app: techcorp
spec:
  type: LoadBalancer
  selector:
    app: techcorp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
